controller_manager:
  ros__parameters:
    update_rate: 30

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names:  ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.219
    wheel_radius: 0.0325

    # по умолчанию odom берётся по position feedback, мы его отдаём
    position_feedback: true
    publish_rate: 30.0
